<Project>
  <PropertyGroup>
    <!-- Own packages -->
    <AssemblyVersion>5.0.0.0</AssemblyVersion>
    <VersionPrefix>5.5.13.6</VersionPrefix>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <!-- Real packages -->
    <MicrosoftSourceLinkGitHubPackageVersion>8.0.0</MicrosoftSourceLinkGitHubPackageVersion>
    <BouncyCastleCryptographyPackageVersion>2.5.1</BouncyCastleCryptographyPackageVersion>
    <SystemDrawingCommonPackageVersion>8.0.13</SystemDrawingCommonPackageVersion>
    <SystemSecurityCryptographyXmlPackageVersion>8.0.2</SystemSecurityCryptographyXmlPackageVersion>
  </PropertyGroup>
  <PropertyGroup>
    <WithoutDrawing>true</WithoutDrawing>
    <WithoutCryptographyXml>true</WithoutCryptographyXml>
  </PropertyGroup>
  <PropertyGroup>
    <SourceLinkCreate>true</SourceLinkCreate>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <GenerateSpecifiedPackagesOnBuild>true</GenerateSpecifiedPackagesOnBuild>
    <RepositoryUrl>https://github.com/komsa-ag/itextsharp</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="$(MicrosoftSourceLinkGitHubPackageVersion)" PrivateAssets="All" />
  </ItemGroup>
</Project>